name: "Build Fedora CoreOS UKI image"

env:
  NAME: "fedora-coreos-uki"
  REGISTRY: "quay.io/travier"

on:
  # pull_request:
  #   branches:
  #     - main
  push:
    # branches:
    #   - main
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

permissions: read-all

# Prevent multiple workflow runs from racing to ensure that pushes are made
# sequentialy for the main branch. Also cancel in progress workflow runs for
# pull requests only.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-push-image:
    runs-on: ubuntu-24.04
    container:
      image: quay.io/coreos-assembler/coreos-assembler:latest
      env:
        COSA_PRIVILEGED: 1
      options: --security-opt=label=disable --privileged --user 0:0 --device=/dev/kvm --device=/dev/fuse --tmpfs=/tmp --volume /var/lib/containers:/var/lib/containers:rw
    steps:
      # - name: Generate a key for ostree signing
      #   run: ./gen-ostree-signing-key

      - name: Build container & qcow2 image
        run: |
          sed -i "s/sudo -E / /g" /usr/lib/coreos-assembler/cmd*
          sed -i "s/sudo / /g" /usr/lib/coreos-assembler/cmd*
          cosa init "https://github.com/travier/fedora-coreos-uki-devel.git"
          cosa build

      - name: Login to Container Registry
        uses: redhat-actions/podman-login@v1
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.BOT_USERNAME }}
          password: ${{ secrets.BOT_SECRET }}

      - name: Push to Container Registry
        run: |
          skopeo copy \
            --retry-times 3 \
            --dest-compress-format gzip \
            oci-archive:builds/latest/x86_64/fedora-coreos*.ociarchive \
            docker://quay.io/travier/fedora-coreos-uki-devel:latest
